// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayPlan.DataModel;

#nullable disable

namespace PlayPlan.Migrations
{
    [DbContext(typeof(PlayPlanContext))]
    [Migration("20220221143905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("PlayPlan.DataModel.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsePhrases")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PlayPlan.DataModel.Setting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonFieldName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicParsePhrases")
                        .HasColumnType("TEXT");

                    b.Property<string>("VkApiVer")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PlayPlan.DataModel.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicCommentsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicCreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TopicDateCreate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TopicDateUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicUpdatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("PlayPlan.DataModel.TopicComment", b =>
                {
                    b.Property<int>("Topic_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInput")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participants")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentFrom")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopicID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Topic_ID");

                    b.HasIndex("TopicID");

                    b.ToTable("TopicComments");
                });

            modelBuilder.Entity("PlayPlan.DataModel.TopicComment", b =>
                {
                    b.HasOne("PlayPlan.DataModel.Topic", null)
                        .WithMany("TopicComments")
                        .HasForeignKey("TopicID");
                });

            modelBuilder.Entity("PlayPlan.DataModel.Topic", b =>
                {
                    b.Navigation("TopicComments");
                });
#pragma warning restore 612, 618
        }
    }
}
